image: nextflow/nextflow:20.10.0

# include: '/environment.yml'

before_script:
  - java -version
  - nextflow help

stages:
  - test

test:
  stage: test
  script:
    #nextflow run
    #- make clean test-conda-aln-single
    - nextflow main.nf -profile test,conda
    - ll output
    #- make clean test-conda-aln-paired
    - nextflow main.nf -profile test,conda --library single
    - ll output
    #- make clean test-conda-mem-single
    - nextflow main.nf -profile test,conda --algorithm mem
    - ll output
    #- make clean test-conda-mem-paired
    - nextflow main.nf -profile test,conda --algorithm mem --library single
    - ll output
