image: openjdk:11.0.10-jre-buster

# include: '/environment.yml'

#variables:
#  PATH: "/root/miniconda3/bin:${PATH}"

before_script:
  - java -version
  - wget -qO- https://get.nextflow.io | bash
  - nextflow help
  - apt-get update && apt-get add wget
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - mkdir /root/.conda
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - rm -f Miniconda3-latest-Linux-x86_64.sh
  - conda --version
  - which conda
  #- conda --version

stages:
  - test

test:
  stage: test
  script:
    #nextflow run
    #- make clean test-conda-aln-single
    - nextflow main.nf -profile test,conda
    - ll output
    #- make clean test-conda-aln-paired
    - nextflow main.nf -profile test,conda --library single
    - ll output
    #- make clean test-conda-mem-single
    - nextflow main.nf -profile test,conda --algorithm mem
    - ll output
    #- make clean test-conda-mem-paired
    - nextflow main.nf -profile test,conda --algorithm mem --library single
    - ll output
