image: nfcore/base:1.9

# include: '/environment.yml'

before_script:
    - conda env create bioconda::bwa=0.7.17 conda-forge::ncurses=5 bioconda::samtools=0.1.16 make=4.2.1 && conda clean -a

stages:
  - test

test:
  stage: test
  script:
    #nextflow run
    - make clean test-conda-aln-single
    - ll output
    - make clean test-conda-aln-paired
    - ll output
    - make clean test-conda-mem-single
    - ll output
    - make clean test-conda-mem-paired
    - ll output
