# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: tronflow-bwa-1.2.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bwa=0.7.17
  - conda-forge::ncurses=5
  - bioconda::samtools=0.1.16