name: Automated tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: conda-incubator/setup-miniconda@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get --assume-yes install wget make procps software-properties-common
        wget -qO- https://get.nextflow.io | bash && cp nextflow /usr/local/bin/nextflow
    - name: Build star indices
      run: |
        #cd test_data
        #conda init bash
        #conda env create -f star_environment.yml
        #conda activate star
        conda install -y bioconda::star=2.7.10a
        STAR --runMode genomeGenerate --genomeDir test_data --genomeFastaFiles test_data/ucsc.hg19.minimal.fasta --sjdbGTFfile test_data/gencode.v37.minimal.gtf
        #./build_star_indexes.sh
        #conda deactivate
        #cd ..
    - name: Run tests
      run: |
        make